/**
 * Shared Receiving Command — Quick Restock / توريد سريع
 *
 * The authoritative implementation of a cash-paid supplier receipt.
 * Used by both Desktop (QuickRestockDialog) and Mobile (MobileQuickRestock).
 *
 * It writes ONE `purchase` event through `buildPurchaseLines` — the SAME
 * builder the invoice screen uses. There is no second receive path: change the
 * shape of a receipt there and this changes with it.
 *
 * It also writes the matching purchase invoice document through
 * `addPurchaseInvoice` so the receipt shows up in that supplier's totals and
 * history exactly like a typed invoice.
 *
 * The supplier belongs to the EVENT, never to the product: the same item comes
 * from المرادي this week and someone else the next, so a "default supplier"
 * field on `Product` would be wrong the first time a second supplier is used.
 *
 * Deliberately cash-paid. The credit split, due date and notes belong to the
 * full invoice form; this command says so explicitly rather than silently
 * dropping the option.
 *
 * Atomicity: All steps succeed or the whole operation fails. No partial
 * updates, no orphan rows, no false success.
 *
 * Idempotency: Caller MUST provide an `idempotencyKey` (e.g., from
 * `useSubmitGate` or a generated UUID). The command itself does not enforce
 * deduplication — that is the caller's responsibility via the submit gate.
 * This keeps the command pure and testable.
 *
 * Security: RLS/backend enforces: unauthenticated/anon/wrong role/expired
 * license/suspended/unlicensed/wrong store/forged store ID all denied.
 * Tenant identity (storeId) is resolved from authenticated membership inside
 * `appendEvent`, NOT from caller-supplied input.
 */

import { useBusinessStore } from "@/store/useBusinessStore";
import { commitReceipt } from "./commitReceipt";
import { readSupplierById } from "./suppliers";
import type { Supplier, WalletType } from "@/types";

export interface QuickRestockLineInput {
  productId: string;
  productName: string;
  sku: string;
  quantity: number;
  unitCost: number;
  variantName?: string;
}

export interface QuickRestockSupplierInput {
  /** Existing supplier ID, or "__new__" to register inline */
  supplierId: string;
  /** Required when supplierId === "__new__" */
  newSupplierName?: string;
  newSupplierPhone?: string;
}

export interface QuickRestockInput {
  /** Lines to receive. At least one required with quantity > 0. */
  lines: QuickRestockLineInput[];
  /** Supplier selection (existing or new) */
  supplier: QuickRestockSupplierInput;
  /** Wallet the cash comes from */
  wallet: WalletType;
  /** Optional note for the invoice document */
  notes?: string;
  /** Unique key generated by caller for idempotency */
  idempotencyKey: string;
}

export interface QuickRestockResult {
  /** The ledger event ID */
  eventId: string;
  /** The purchase invoice number (FM-XXXX) */
  invoiceNumber: string;
  /** The supplier the receipt was recorded against */
  supplier: Supplier;
  /** Total amount of the receipt */
  total: number;
  /** Number of lines received */
  itemCount: number;
}

/** Sentinel for "this supplier is not registered yet". */
export const NEW_SUPPLIER = "__new__";

/**
 * Execute a quick restock (توريد سريع).
 *
 * @throws {Error} If validation fails, supplier not found/created, ledger write fails, or invoice write fails.
 *   The error message is user-facing in Arabic.
 */
export async function executeQuickRestock(input: QuickRestockInput): Promise<QuickRestockResult> {
  // ── Validation ─────────────────────────────────────────────────────────
  if (!input.lines || input.lines.length === 0) {
    throw new Error("لا توجد أصناف للتوريد");
  }

  const validLines = input.lines.filter((l) => l.quantity > 0);
  if (validLines.length === 0) {
    throw new Error("يجب إدخال كمية أكبر من صفر لصنف واحد على الأقل");
  }

  // Validate each line
  for (const line of validLines) {
    if (line.quantity <= 0) {
      throw new Error(`الكمية لـ "${line.productName}" يجب أن تكون أكبر من صفر`);
    }
    if (line.unitCost < 0) {
      throw new Error(`تكلفة الوحدة لـ "${line.productName}" لا يمكن أن تكون سالبة`);
    }
  }

  // ── 1. Resolve or create the supplier ──────────────────────────────────
  //
  // Resolved SERVER-SIDE, not from `useBusinessStore.suppliers`. That array is
  // populated by `hydrateAll`, which mobile deliberately never calls — so on
  // mobile it was always empty, every existing supplier looked missing, and the
  // operator was pushed down the "register new" branch on every single receipt.
  // The result was a fresh duplicate supplier each time, with that supplier's
  // payable fragmented across all of them.
  const supplier = await resolveReceiptSupplier(input.supplier);

  // ── 2. Write it, through the one safe path ─────────────────────────────
  const result = await commitReceipt({
    supplierId: supplier.id,
    supplierName: supplier.companyName,
    items: validLines.map((l) => ({
      productId: l.productId,
      productName: l.productName,
      sku: l.sku,
      quantity: l.quantity,
      unitCost: l.unitCost,
      variantName: l.variantName,
    })),
    wallet: input.wallet,
    // Deliberately cash-paid in full: the credit split, due date and terms
    // belong to the full invoice form, and this command says so rather than
    // silently dropping the option.
    paidAmount: Number.POSITIVE_INFINITY,
    notes: input.notes ?? "توريد سريع من شاشة المنتجات",
    actor: "توريد",
    via: "quick_restock",
    payloadExtra: { idempotencyKey: input.idempotencyKey },
  });

  return {
    eventId: result.eventId,
    invoiceNumber: result.invoiceNumber,
    supplier,
    total: result.total,
    itemCount: result.itemCount,
  };
}

/**
 * The supplier this receipt belongs to, from the database.
 *
 * An existing id is verified against the server rather than against whatever
 * the local store happens to hold, so the same call works on desktop (hydrated)
 * and mobile (not hydrated). A new supplier is only ever created when the
 * caller explicitly asked for one.
 */
async function resolveReceiptSupplier(
  selection: QuickRestockSupplierInput,
): Promise<Supplier> {
  const { supplierId, newSupplierName, newSupplierPhone } = selection;

  if (supplierId === NEW_SUPPLIER) {
    const name = newSupplierName?.trim();
    if (!name) throw new Error("اسم المورد مطلوب عند إضافة مورد جديد");
    const created = await useBusinessStore.getState().addSupplier({
      companyName: name,
      contactPerson: "",
      phone: newSupplierPhone?.trim() ?? "",
    });
    if (!created?.id) throw new Error("فشل إنشاء المورد — لم يُرجع معرفًا");
    return created;
  }

  if (!supplierId) throw new Error("المورد المحدد غير موجود");

  const found = await readSupplierById(supplierId);
  if (!found?.id) throw new Error("المورد المحدد غير موجود");
  return found as Supplier;
}

/**
 * Format a user-facing success message for a quick restock result.
 */
export function formatQuickRestockSuccess(result: QuickRestockResult): string {
  return result.itemCount > 1
    ? `اتسجّل توريد ${result.itemCount} أصناف باسم ${result.supplier.companyName}`
    : `اتسجّل التوريد باسم ${result.supplier.companyName}`;
}