/**
 * Shared Receiving Command — Quick Restock / توريد سريع
 *
 * The authoritative implementation of a cash-paid supplier receipt.
 * Used by both Desktop (QuickRestockDialog) and Mobile (MobileQuickRestock).
 *
 * It writes ONE `purchase` event through `buildPurchaseLines` — the SAME
 * builder the invoice screen uses. There is no second receive path: change the
 * shape of a receipt there and this changes with it.
 *
 * It also writes the matching purchase invoice document through
 * `addPurchaseInvoice` so the receipt shows up in that supplier's totals and
 * history exactly like a typed invoice.
 *
 * The supplier belongs to the EVENT, never to the product: the same item comes
 * from المرادي this week and someone else the next, so a "default supplier"
 * field on `Product` would be wrong the first time a second supplier is used.
 *
 * Deliberately cash-paid. The credit split, due date and notes belong to the
 * full invoice form; this command says so explicitly rather than silently
 * dropping the option.
 *
 * Atomicity: All steps succeed or the whole operation fails. No partial
 * updates, no orphan rows, no false success.
 *
 * Idempotency: Caller MUST provide an `idempotencyKey` (e.g., from
 * `useSubmitGate` or a generated UUID). The command itself does not enforce
 * deduplication — that is the caller's responsibility via the submit gate.
 * This keeps the command pure and testable.
 *
 * Security: RLS/backend enforces: unauthenticated/anon/wrong role/expired
 * license/suspended/unlicensed/wrong store/forged store ID all denied.
 * Tenant identity (storeId) is resolved from authenticated membership inside
 * `appendEvent`, NOT from caller-supplied input.
 */

import { appendEvent } from "@/lib/ledger";
import { buildPurchaseLines, purchaseTotal, type PurchaseLineItem } from "@/lib/ledger/purchases";
import { useBusinessStore } from "@/store/useBusinessStore";
import type { Supplier, PurchaseInvoice, Product, WalletType } from "@/types";

export interface QuickRestockLineInput {
  productId: string;
  productName: string;
  sku: string;
  quantity: number;
  unitCost: number;
  variantName?: string;
}

export interface QuickRestockSupplierInput {
  /** Existing supplier ID, or "__new__" to register inline */
  supplierId: string;
  /** Required when supplierId === "__new__" */
  newSupplierName?: string;
  newSupplierPhone?: string;
}

export interface QuickRestockInput {
  /** Lines to receive. At least one required with quantity > 0. */
  lines: QuickRestockLineInput[];
  /** Supplier selection (existing or new) */
  supplier: QuickRestockSupplierInput;
  /** Wallet the cash comes from */
  wallet: WalletType;
  /** Optional note for the invoice document */
  notes?: string;
  /** Unique key generated by caller for idempotency */
  idempotencyKey: string;
}

export interface QuickRestockResult {
  /** The ledger event ID */
  eventId: string;
  /** The purchase invoice number (FM-XXXX) */
  invoiceNumber: string;
  /** The supplier the receipt was recorded against */
  supplier: Supplier;
  /** Total amount of the receipt */
  total: number;
  /** Number of lines received */
  itemCount: number;
}

/** Sentinel for "this supplier is not registered yet". */
export const NEW_SUPPLIER = "__new__";

/**
 * Execute a quick restock (توريد سريع).
 *
 * @throws {Error} If validation fails, supplier not found/created, ledger write fails, or invoice write fails.
 *   The error message is user-facing in Arabic.
 */
export async function executeQuickRestock(input: QuickRestockInput): Promise<QuickRestockResult> {
  // ── Validation ─────────────────────────────────────────────────────────
  if (!input.lines || input.lines.length === 0) {
    throw new Error("لا توجد أصناف للتوريد");
  }

  const validLines = input.lines.filter((l) => l.quantity > 0);
  if (validLines.length === 0) {
    throw new Error("يجب إدخال كمية أكبر من صفر لصنف واحد على الأقل");
  }

  // Validate each line
  for (const line of validLines) {
    if (line.quantity <= 0) {
      throw new Error(`الكمية لـ "${line.productName}" يجب أن تكون أكبر من صفر`);
    }
    if (line.unitCost < 0) {
      throw new Error(`تكلفة الوحدة لـ "${line.productName}" لا يمكن أن تكون سالبة`);
    }
  }

  const { suppliers, addSupplier, addPurchaseInvoice, purchaseInvoices } = useBusinessStore.getState();

  // ── 1. Resolve or create supplier ──────────────────────────────────────
  let supplier: Supplier;
  const { supplierId, newSupplierName, newSupplierPhone } = input.supplier;
  const registeringNew = supplierId === NEW_SUPPLIER;

  if (registeringNew) {
    const name = newSupplierName?.trim();
    if (!name) {
      throw new Error("اسم المورد مطلوب عند إضافة مورد جديد");
    }
    supplier = await addSupplier({
      companyName: name,
      contactPerson: "",
      phone: newSupplierPhone?.trim() ?? "",
    });
    if (!supplier?.id) {
      throw new Error("فشل إنشاء المورد — لم يُرجع معرفًا");
    }
  } else {
    supplier = suppliers.find((s) => s.id === supplierId);
    if (!supplier?.id) {
      throw new Error("المورد المحدد غير موجود");
    }
  }

  // ── 2. Build ledger lines and total ────────────────────────────────────
  const total = purchaseTotal(
    validLines.map((l) => ({
      productId: l.productId,
      quantity: l.quantity,
      unitCost: l.unitCost,
    }))
  );

  // Same numbering as the invoice screen, off the same list, so the
  // sequence stays continuous however the receipt was entered.
  const invoiceNumber = "FM-" + String(purchaseInvoices.length + 1).padStart(4, "0");

  // ONE event. Same builder as the invoice screen: stock + (qty AND value,
  // which is what keeps the weighted-average cost derivable) and the cash
  // leaving the chosen wallet. Paid in full, so no supplier debt is booked.
  const ledgerLines = buildPurchaseLines({
    items: validLines.map((l) => ({
      productId: l.productId,
      quantity: l.quantity,
      unitCost: l.unitCost,
      variantName: l.variantName,
    })),
    wallet: input.wallet,
    supplierId: supplier.id,
    paidAmount: total,
  });

  // ── 3. Append ledger event (atomic: stock + wallet + payable) ──────────
  let ledgerWritten = false;
  let eventId: string;
  try {
    eventId = await appendEvent({
      kind: "purchase",
      actor: "توريد",
      refType: "supplier_invoice",
      refId: invoiceNumber,
      payload: {
        invoiceNumber,
        supplierName: supplier.companyName,
        itemCount: validLines.length,
        wallet: input.wallet,
        via: "quick_restock",
        idempotencyKey: input.idempotencyKey,
      },
      lines: ledgerLines,
    });
    ledgerWritten = true;
  } catch (e) {
    throw new Error(`فشل تسجيل التوريد في دفتر الحسابات: ${e instanceof Error ? e.message : String(e)}`);
  }

  // ── 4. Apply stock moves to local mirror (instant UI feedback) ─────────
  // This mirrors what the ledger event will eventually aggregate to.
  // The ledger remains the source of truth; this is for immediate UI.
  useBusinessStore.getState().applyStockMoves(
    validLines.map((line) => ({
      productId: line.productId,
      delta: line.quantity,
      variantName: line.variantName,
    }))
  );

  // ── 5. Write purchase invoice document ─────────────────────────────────
  // A supplier invoice with no stock behind it is the drift we delete
  // everywhere else. This is what makes the receipt show up in that
  // supplier's totals and history.
  //
  // Awaited and caught SEPARATELY: by this point the stock and the money
  // are already in the ledger, so telling the user "nothing was saved"
  // would be a lie that makes them enter the receipt twice.
  try {
    await addPurchaseInvoice({
      invoiceNumber,
      supplierId: supplier.id,
      supplierName: supplier.companyName,
      items: validLines.map((l) => ({
        id: crypto.randomUUID(),
        productId: l.productId,
        productName: l.productName,
        sku: l.sku,
        quantity: l.quantity,
        unitCost: l.unitCost,
        total: l.quantity * l.unitCost,
      })),
      totalAmount: total,
      paidAmount: total,
      remainingAmount: 0,
      dueDate: new Date().toISOString().slice(0, 10),
      status: "paid",
      notes: input.notes ?? "توريد سريع من شاشة المنتجات",
    });
  } catch (e) {
    const detail = e instanceof Error ? e.message : String(e);
    // The ledger event SUCCEEDED — stock and cash HAVE moved.
    // Re-entering the receipt would double it.
    throw new Error(
      `المخزون والفلوس اتسجّلوا، لكن فاتورة المورد متسجّلتش. ` +
        `متعملش التوريد تاني — سجّل الفاتورة من شاشة المشتريات. ${detail}`
    );
  }

  return {
    eventId,
    invoiceNumber,
    supplier,
    total,
    itemCount: validLines.length,
  };
}

/**
 * Format a user-facing success message for a quick restock result.
 */
export function formatQuickRestockSuccess(result: QuickRestockResult): string {
  return result.itemCount > 1
    ? `اتسجّل توريد ${result.itemCount} أصناف باسم ${result.supplier.companyName}`
    : `اتسجّل التوريد باسم ${result.supplier.companyName}`;
}