/**
 * Licence-key generation and the date arithmetic behind the expiry picker.
 *
 * Split out of the screen and the service so `scripts/check_license_key.mjs`
 * can import them without dragging in Supabase or React. Both are small enough
 * to look obviously correct and both are wrong in ways that are invisible
 * until a customer is affected — a predictable key, or a licence that expires
 * a day early for anyone east of UTC.
 */

/** No I, O, 0 or 1 — a key gets read down a phone line. */
const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

/**
 * A licence key with real entropy.
 *
 * `crypto.getRandomValues`, never `Math.random()`: a key derived from a
 * timestamp-seeded PRNG can be regenerated by anyone who knows roughly when it
 * was issued. 16 symbols from a 32-symbol alphabet is 80 bits.
 *
 * The modulo is unbiased here only because 32 divides 2^32 exactly; with an
 * alphabet whose length is not a power of two this would need rejection
 * sampling. Change the alphabet and that stops being true.
 */
export function generateLicenseKey(
  plan: "BASIC" | "PRO",
  randomValues: (n: number) => Uint32Array = defaultRandom,
): string {
  const bytes = randomValues(16);
  const chars = Array.from(bytes, (b) => ALPHABET[b % ALPHABET.length]);
  const groups = [
    chars.slice(0, 4).join(""),
    chars.slice(4, 8).join(""),
    chars.slice(8, 12).join(""),
    chars.slice(12, 16).join(""),
  ];
  return `NEXUS-${plan}-${groups.join("-")}`;
}

function defaultRandom(n: number): Uint32Array {
  const out = new Uint32Array(n);
  crypto.getRandomValues(out);
  return out;
}

/**
 * `YYYY-MM-DD` for `<input type="date">`, in the viewer's OWN timezone.
 *
 * `d.toISOString().slice(0,10)` is the tempting one-liner and it is wrong: it
 * converts to UTC first, so at 01:00 in Cairo (UTC+2/+3) it yields yesterday.
 * The picker would open on the wrong day and a one-year licence would be issued
 * a day short.
 */
export function toDateInput(d: Date): string {
  const local = new Date(d.getTime() - d.getTimezoneOffset() * 60_000);
  return local.toISOString().slice(0, 10);
}

/**
 * The quick-pick buttons: +1 / +3 / +6 / +12 months from today.
 *
 * Clamped to the last day of the target month. Plain `setMonth` overflows —
 * 30 August + 6 months is 30 February, which JS silently rolls to 2 March. A
 * "6 شهور" button that produces a date in the wrong month reads as a bug to
 * whoever is issuing the licence, so the day is pinned instead.
 */
export function plusMonths(months: number, from: Date = new Date()): string {
  const day = from.getDate();
  const d = new Date(from.getTime());
  // Move to the 1st first, so the month arithmetic cannot overflow on its own.
  d.setDate(1);
  d.setMonth(d.getMonth() + months);
  // Day 0 of the NEXT month is the last day of this one.
  const lastDay = new Date(d.getFullYear(), d.getMonth() + 1, 0).getDate();
  d.setDate(Math.min(day, lastDay));
  return toDateInput(d);
}

/**
 * The chosen day's LAST moment, local time.
 *
 * "Valid until the 30th" must mean the shop works all day on the 30th. Taking
 * the date at midnight would expire the licence as the 30th begins, cutting a
 * full day off every licence ever issued.
 */
export function endOfDayIso(dateInput: string): string | null {
  const d = new Date(`${dateInput}T23:59:59`);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
}
